[package]
name = "sha2_crates_io_kernels"
version = "0.1.0"
edition = "2024"

[dependencies]
cuda_std = { path = "../../../../crates/cuda_std" }
sha2 = { version = "0.10", default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]