[package]
name = "sha2_crates_io"
version = "0.1.0"
edition = "2024"

[dependencies]
cust = { path = "../../../crates/cust" }
sha2_crates_io_kernels = { path = "kernels" }
sha2 = "0.10"

[build-dependencies]
cuda_builder = { path = "../../../crates/cuda_builder" }